_BASE_: "Base-CenterMask-VoVNet.yaml"
MODEL:
  WEIGHTS: ""
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 2
INPUT:
  MIN_SIZE_TRAIN: (128,128)
OUTPUT_DIR: "output/centermask/CenterMask-V-39-ms-3x"
