_BASE_: "Base-CenterMask-Lite-VoVNet.yaml"
MODEL:
  WEIGHTS: "weights/centermask2-lite-V-39-eSE-FPN-ms-4x.pth"
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (300000, 340000)
  MAX_ITER: 360000
OUTPUT_DIR: "output/centermask/CenterMask-Lite-V-39-ms-4x"
