_BASE_: "Base-CenterMask-VoVNet.yaml"
MODEL:
  WEIGHTS: "weights/centermask2-V-99-eSE-FPN-ms-3x.pth"
  VOVNET:
    CONV_BODY : "V-99-eSE"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/centermask/CenterMask-V-99-ms-3x"
